{
  "hash": "ec6dff2c8587159ee121cc1ca2a19ecf",
  "result": {
    "engine": "jupyter",
    "markdown": "# Limpieza e imputación de datos\n\nExplorar y analizar datos a menudo significa tratar con valores perdidos, tipos de datos incorrectos y valores atípicos. En este capítulo, aprenderás técnicas para gestionar estos problemas y agilizar tus procesos en EDA.\n\n## Tratar los datos que faltan\n\n-   Por qué un dato faltante es un problema?\n\n    -   Afectan las distribuciones\n    -   Los datos de la población son menos repreesntativos\n    -   Puede resultar en conclusiones incorrectas\n\n-   Ejemplo datos de profesionales de datos\n\n| Column | Description | Data type |\n|--------------------|---------------------------------|-------------------|\n| `Working_Year` | Year the data was obtained | Float |\n| `Designation` | Job title | String |\n| `Experience` | Experience level e.g., `\"Mid\"`, `\"Senior\"` | String |\n| `Employment_Satus` | Type of employment contract e.g., `\"FT\"`, `\"PT\"` | String |\n| `Employee_Location` | Country of employment | String |\n| `Company_Size` | Labels for company size e.g., `\"S\"`, `\"M\"`, `\"L\"` | String |\n| `Remote_Working_Ratio` | Porcentage of time working remotely | Integer |\n| `Salary_USD` | Salary in US dollars | Float |\n\n-   Revisando los datos faltantes\n\n::: {#a023475f .cell execution_count=1}\n``` {.python .cell-code}\nprint(salaries.isna().sum())\n```\n:::\n\n\n![](images/paste-22.png)\n\n-   Estrategias para el manejo de datos faltantes\n\n    -   Eliminar los datos faltantes\n\n        -   5 % o menos del total de valores\n\n    -   Imputar la media, mediana o la moda\n\n        -   Depende de la distribución y contexto\n\n    -   Imputar por sub-grupos\n\n        -   Diferentes niveles de experiencia tienen diferente mediana en el salario\n\n-   Eliminando valores faltantes\n\n::: {#c191c22e .cell execution_count=2}\n``` {.python .cell-code}\nthreshold = len(salaries) * 0.05\nprint(threhold)\n```\n:::\n\n\n![](images/paste-23.png)\n\n::: {#2b297446 .cell execution_count=3}\n``` {.python .cell-code}\ncols_to_drop = salaries.columns[salaries.isna().sum() <= threshold]\nprint(cols_to_drop)\n```\n:::\n\n\n![](images/paste-24.png)\n\n::: {#7aa4ff12 .cell execution_count=4}\n``` {.python .cell-code}\nsalaries.dropna(subset=cols_to_drop, inplace=True) # Para actualizar el DataFrame\n```\n:::\n\n\n-   Imputando una estadística de resumen\n\n::: {#3730001a .cell execution_count=5}\n``` {.python .cell-code}\ncols_with_missing_values = salaries.columns[salaries.isna().sum() > 0]\nprint(cols_with_missing_values)\n```\n:::\n\n\n![](images/paste-25.png)\n\n::: {#8c5cbde3 .cell execution_count=6}\n``` {.python .cell-code}\n    for col in cols_with_missing_values[:-1]:\n        salaries[col].fillna(salaries[col].mode()[0])\n```\n:::\n\n\n-   Revisando los valores faltantes que faltan\n\n::: {#2655b6df .cell execution_count=7}\n``` {.python .cell-code}\nprint(salaries.isna().sum())\n```\n:::\n\n\n![](images/paste-26.png)\n\n-   Imputando por subgrupo\n\n::: {#ebb4ef60 .cell execution_count=8}\n``` {.python .cell-code}\nsalaries_dict = salaries.groupby('Experience')['Salary_USD'].median().to_dict()\nprint(salaries_dict)\n```\n:::\n\n\n![](images/paste-27.png)\n\n::: {#12e282a9 .cell execution_count=9}\n``` {.python .cell-code}\nsalaries['Salary_USD'] = salaries['Salary_USD'].fillna(salaries['Experience'].map(salaries_dict))\n```\n:::\n\n\n![](images/paste-28.png)\n\n### Tratar los datos que faltan\n\nEs importante tratar los datos que faltan antes de empezar el análisis.\n\nUn enfoque consiste en descartar los valores que faltan si representan una pequeña proporción, normalmente el 5 %, de los datos.\n\nTrabajando con un conjunto de datos sobre precios de tiquetes de avión, almacenado como un DataFrame de pandas llamado `planes`, tendrás que contar el número de valores perdidos en todas las columnas, calcular el cinco porciento de todos los valores, utilizar este umbral para eliminar observaciones y comprobar cuántos valores perdidos quedan en el conjunto de datos.\n\n::: {#e5c0e955 .cell execution_count=10}\n``` {.python .cell-code}\nimport pandas as pd\n\nruta = './data/planes.csv'\nplanes = pd.read_csv(ruta)\nprint(planes.head)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<bound method NDFrame.head of            Airline Date_of_Journey    Source Destination  \\\n0      Jet Airways       9/06/2019     Delhi      Cochin   \n1           IndiGo      12/05/2019   Kolkata    Banglore   \n2           IndiGo      01/03/2019  Banglore   New Delhi   \n3         SpiceJet      24/06/2019   Kolkata    Banglore   \n4      Jet Airways      12/03/2019  Banglore   New Delhi   \n...            ...             ...       ...         ...   \n10655     Air Asia       9/04/2019   Kolkata    Banglore   \n10656    Air India      27/04/2019   Kolkata    Banglore   \n10657  Jet Airways      27/04/2019  Banglore       Delhi   \n10658      Vistara      01/03/2019  Banglore   New Delhi   \n10659    Air India       9/05/2019     Delhi      Cochin   \n\n                       Route Dep_Time  Arrival_Time Duration Total_Stops  \\\n0      DEL → LKO → BOM → COK    09:25  04:25 10 Jun      19h     2 stops   \n1            CCU → NAG → BLR    18:05         23:30   5h 25m      1 stop   \n2            BLR → NAG → DEL    16:50         21:35   4h 45m      1 stop   \n3                  CCU → BLR    09:00         11:25   2h 25m    non-stop   \n4            BLR → BOM → DEL    18:55  10:25 13 Mar  15h 30m      1 stop   \n...                      ...      ...           ...      ...         ...   \n10655              CCU → BLR    19:55         22:25   2h 30m    non-stop   \n10656              CCU → BLR    20:45         23:20   2h 35m    non-stop   \n10657              BLR → DEL      NaN         11:20       3h    non-stop   \n10658              BLR → DEL    11:30         14:10   2h 40m    non-stop   \n10659  DEL → GOI → BOM → COK    10:55         19:15   8h 20m     2 stops   \n\n                   Additional_Info    Price  \n0                          No info  13882.0  \n1                          No info   6218.0  \n2                          No info  13302.0  \n3                          No info   3873.0  \n4      In-flight meal not included  11087.0  \n...                            ...      ...  \n10655                      No info   4107.0  \n10656                      No info   4145.0  \n10657                          NaN   7229.0  \n10658                      No info  12648.0  \n10659                      No info  11753.0  \n\n[10660 rows x 11 columns]>\n```\n:::\n:::\n\n\n#### Instrucciones\n\n1.  Imprime el número de valores perdidos en cada columna del DataFrame\n\n::: {#38e4d811 .cell execution_count=11}\n``` {.python .cell-code}\n# Count the number of missing values in each column\nprint(planes.isna().sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAirline            427\nDate_of_Journey    322\nSource             187\nDestination        347\nRoute              256\nDep_Time           260\nArrival_Time       194\nDuration           214\nTotal_Stops        212\nAdditional_Info    589\nPrice              616\ndtype: int64\n```\n:::\n:::\n\n\n2.  Calcula a cuántas observaciones equivale el cinco porciento del DataFrame `planes`\n\n::: {#1784140a .cell execution_count=12}\n``` {.python .cell-code}\n# Find the five percent threshold\nthreshold = len(planes) * 0.05\nprint(threshold)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n533.0\n```\n:::\n:::\n\n\n3.  \n\n-   Crea `cols_to_drop` aplicando una indexación booleana a las columnas del DataFrame con valores perdidos menores o iguales que el umbral.\n\n-   Utiliza este filtro para eliminar los valores que faltan y guardar el DataFrame actualizado.\n\n::: {#2bb0c910 .cell execution_count=13}\n``` {.python .cell-code}\n# Create a filter\ncols_to_drop = planes.columns[planes.isna().sum() <= threshold]\nprint(cols_to_drop)\n\n# Drop missing values for columns below the threshold\nplanes.dropna(subset=cols_to_drop, inplace=True)\n\nprint(planes.isna().sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIndex(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',\n       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops'],\n      dtype='object')\nAirline              0\nDate_of_Journey      0\nSource               0\nDestination          0\nRoute                0\nDep_Time             0\nArrival_Time         0\nDuration             0\nTotal_Stops          0\nAdditional_Info    300\nPrice              368\ndtype: int64\n```\n:::\n:::\n\n\nAl crear un umbral de valores faltantes y usarlo para filtrar columnas, haz logrado eliminar los valores faltantes de todas las columnas excepto `\"Additinal_Info\"` y `\"Price\"`.\n\n### Estrategias para datos que faltan\n\nLa regla del cinco porciento ha funcionado muy bien en tu conjunto de dato `planes`, ¡eliminando los valores perdidos de nueve de las 11 columnas!\n\nAhora tienes que decidir qué hacer con las columnas `\"Additional_Info\"` y `\"Price\"`, a las que les faltan los valores `300` y `368` respectivamente.\n\nPrimero echarás un vistazo a lo que contiene `\"Additional_Info\"`, y después visualizarás el precio de los billetes de avión de distintas compañías aéreas.\n\n::: {#8829d8b5 .cell execution_count=14}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n```\n:::\n\n\n#### Instrucciones\n\n1.  Imprime los valores y frecuencias de `\"Additional_Info\"`.\n\n::: {#f5d4a958 .cell execution_count=15}\n``` {.python .cell-code}\n# Check the values of the Additional_Info column\nprint(planes['Additional_Info'].value_counts())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAdditional_Info\nNo info                         6399\nIn-flight meal not included     1525\nNo check-in baggage included     258\n1 Long layover                    14\nChange airports                    7\nNo Info                            2\nBusiness class                     1\nRed-eye flight                     1\n2 Long layover                     1\nName: count, dtype: int64\n```\n:::\n:::\n\n\n2.  Crea un boxplot de `\"Price\"` frente a `\"Airline\"`\n\n::: {#d3692a50 .cell execution_count=16}\n``` {.python .cell-code}\n# Create a box plot of Price by Airline\nsns.boxplot(data=planes, x='Airline', y='Price',\n            hue='Airline', legend=False)\n\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](02_Limpieza_e_imputacion_de_datos_files/figure-html/cell-17-output-1.png){}\n:::\n:::\n\n\n3.  **Pregunta**\n\n-   ¿Cómo debes tratar los valores que faltan en `\"Additional_Info\"` y `\"Price\"`.?\n\n**Respuestas Posibles**\n\n-   [ ] Elimina la columna `\"Additional_Info\"` e imputa la media para los valores que faltan de `\"Price\"`.\n-   [ ] Elimina los valores de `\"No info\"` de `\"Additiona_Info\"` e imputa la mediana de los valores que faltan de `\"Price\"`.\n-   [ ] Elimina la columna `\"Additional_Info\"` e imputa la media por `\"Airline\"` para los valores que falten de `\"Price\"`.\n-   [x] Elimina la columna `\"Additional_Info\"` e imputa la mediana por `\"Airline\"` para los valores que falten de `\"Price\"`.\n\nNo necesitamos la columna `\"Additional_Info\"`, y deberías imputar la mediana de `\"Price\"` por `\"Airline\"` para representar los datos con precisión.\n\n### Imputar los precios de los aviones que faltan\n\n!Ahora solo queda una columna con valores perdidos!\n\nHas eliminado la columna `\"Additional_Info\"` de `planes`, el último paso es imputar los datos que faltan en la columna `\"Price\"` del conjunto de datos.\n\nComo recordatorio, tú generaste este diagrama de caja, que sugería que imputar el precio medio basándose en el `\"Airline\"` ¡es un enfoque sólido!\n\n::: {#3bbab532 .cell execution_count=17}\n``` {.python .cell-code}\n# Eliminamos la columna Additional_Info\nplanes = planes.drop('Additional_Info', axis=1)\nplanes.columns\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```\nIndex(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',\n       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops', 'Price'],\n      dtype='object')\n```\n:::\n:::\n\n\n#### Instrucciones\n\n1.  Agrupa `planes` por aerolínea y calcula el precio medio.\n\n::: {#3a9628a3 .cell execution_count=18}\n``` {.python .cell-code}\n# Calculate median plane ticket prices by Airplane\nairline_prices = planes.groupby('Airline')['Price'].median()\n\nprint(airline_prices)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAirline\nAir Asia              5192.0\nAir India             9443.0\nGoAir                 5003.5\nIndiGo                5054.0\nJet Airways          11507.0\nMultiple carriers    10197.0\nSpiceJet              3873.0\nVistara               8028.0\nName: Price, dtype: float64\n```\n:::\n:::\n\n\n2.  Convierte los precios medios agrupados en un diccionario.\n\n::: {#5c034181 .cell execution_count=19}\n``` {.python .cell-code}\n# Convert to a dictionary\nprices_dict = airline_prices.to_dict()\nprint(prices_dict)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n{'Air Asia': 5192.0, 'Air India': 9443.0, 'GoAir': 5003.5, 'IndiGo': 5054.0, 'Jet Airways': 11507.0, 'Multiple carriers': 10197.0, 'SpiceJet': 3873.0, 'Vistara': 8028.0}\n```\n:::\n:::\n\n\n3.  \n\n-   Imputa condicionalmente los valores perdidos de `\"Price\"` asignando los valores de la columna `\"Airline\"` en función de `prices_dict`\n\n-   Comprueba si faltan valores\n\n::: {#ac7886c2 .cell execution_count=20}\n``` {.python .cell-code}\n# Map the dictionary to missing values of Price by Airline\nplanes['Price'] = planes['Price'].fillna(planes['Airline'].map(prices_dict))\n\n# Check for missing values\nprint(planes.isna().sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAirline            0\nDate_of_Journey    0\nSource             0\nDestination        0\nRoute              0\nDep_Time           0\nArrival_Time       0\nDuration           0\nTotal_Stops        0\nPrice              0\ndtype: int64\n```\n:::\n:::\n\n\nConvertiste un DataFrame agrupado a un diccionario y luego lo usaste para llenar condicionalmente los valores faltantes de `\"Price\"` basándote en `\"Airline\"`. Ahora vamos a explorar cómo realizar análisis exploratorio en datos categóricos.\n\n## Convertir y analizar datos categóricos\n\n-   Previsualizar los datos\n\n::: {#ef70c951 .cell execution_count=21}\n``` {.python .cell-code}\nprint(salaries.select_dtypes('object').head())\n```\n:::\n\n\n![](images/paste-29.png)\n\n-   Títulos de los trabajos\n\n::: {#97987a1d .cell execution_count=22}\n``` {.python .cell-code}\nprint(salaries['Designation'].value_counts())\n```\n:::\n\n\n![](images/paste-30.png)\n\n::: {#8a63165e .cell execution_count=23}\n``` {.python .cell-code}\nprint(salaries['Designation'].nunique())\n```\n:::\n\n\n![](images/paste-31.png)\n\n![](images/paste-32.png)\n\n-   Extrayendo valores desde las categorías\n\n    -   El formato actual de los datos limita la capacidad de generar información.\n\n    -   `pandas.Series.str.contains()`\n\n        -   Busca en una columna una cadena especifica o múltiples cadenas.\n\n::: {#41473f52 .cell execution_count=24}\n``` {.python .cell-code}\nsalaries['Designation'].str.contains('Scientist')\n```\n:::\n\n\n![](images/paste-33.png)\n\n-   Filtrar filas que contienen una o más frases\n\n    -   Palabras de interes: Machine Learning o AI\n\n::: {#bca43efe .cell execution_count=25}\n``` {.python .cell-code}\nsalaries['Designation'].str.contains('Machine Learning|AI')\n```\n:::\n\n\n![](images/paste-34.png)\n\n-   Buscar múltiples frases en una cadena de caracteres\n\n    -   Palabras de interes: Cualquiera que inicie con Data\n\n::: {#1c4321a7 .cell execution_count=26}\n``` {.python .cell-code}\nsalaries['Designation'].str.contains('ˆData')\n```\n:::\n\n\n![](images/paste-35.png)\n\nAhora que se tiene una idea de cómo funciona este método, definamos una lista de títulos de trabajo que queremos encontrar:\n\n::: {#9babbe06 .cell execution_count=27}\n``` {.python .cell-code}\njob_categories = ['Data Science', 'Data Analytics',\n                   'Data Engineering', 'Machine Learning',\n                   'Managerial', 'Consultant']\n```\n:::\n\n\nLuego necesitamos crear variables que contengan nuestros filtros\n\n::: {#e8240310 .cell execution_count=28}\n``` {.python .cell-code}\ndata_science = 'Data Scientist|NLP'\ndata_analyst = 'Analyst|Analytics'\ndata_engineer = 'Data Engineer|ETL|Architect|Infrastructure'\nml_engineer = 'Machine Learning|ML|Bid Data|AI'\nmanager = 'Manager|Head|Director|Lead|Principal|Staff'\nconsultant = 'Consultant|Freelance'\n```\n:::\n\n\nEl siguiente paso es crear una lista con nuestro rango de condiciones para el método `str.contains`\n\n::: {#9fee9a12 .cell execution_count=29}\n``` {.python .cell-code}\nconditions = [\n    (salaries['Designation'].str.contains(data_science)),\n    (salaries['Designation'].str.contains(data_analyst)),\n    (salaries['Designation'].str.contains(data_engineer)),\n    (salaries['Designation'].str.contains(ml_engineer)),\n    (salaries['Designation'].str.contains(manager)),\n    (salaries['Designation'].str.contains(consultant))\n]\n```\n:::\n\n\nFinalmente, podemos crear nuestra nueva columna `Job_Category` usando la función de selección de Numpy\n\n::: {#e0fe14df .cell execution_count=30}\n``` {.python .cell-code}\nsalaries['Job_Category'] = np.select(conditions,\n                                     job_categories,\n                                     default='Other')\n```\n:::\n\n\nAl obtener una vista previa de la Designación y nuestra nueva columna Job_Category, podemos verificar los primeros cinco valores.\n\n::: {#38c031ac .cell execution_count=31}\n``` {.python .cell-code}\nprint(salaries[['Designation', 'Job_Category']].head())\n```\n:::\n\n\n![](images/paste-36.png)\n\n-   Visualización de la frecuencia de la categoría job\n\n::: {#e34e6e96 .cell execution_count=32}\n``` {.python .cell-code}\nsns.countplot(data=salaries, x='Job_Category')\nplt.show()\n```\n:::\n\n\n![](images/paste-37.png)\n\n### Encontrar el número de valores únicos\n\nTe gustaría practicar algunas de las habilidades de manipulación y análisis de datos categóricos que acabas de ver. Para ayudarte a identificar qué datos podrían reformatearse para extraer valor, vas a averiguar qué columnas no numéricas del conjunto de datos `planes` tienen un gran número de valores únicos.\n\n#### Instrucciones\n\n-   Filtra `planes` para las columnas que sean del tipo datos `\"object\"`.\n\n-   Recorre las columnas del conjunto de datos.\n\n-   Añade el iterador de columna a la sentencia print y, a continucación, llama a la función para que devuelva el número de valores únicos de la columna.\n\n::: {#da063e1d .cell execution_count=33}\n``` {.python .cell-code}\n# Filter the DataFrame for objects columns\nnon_numeric = planes.select_dtypes('object')\n\n# Loop through columns\nfor column in non_numeric.columns:\n    # Print the number of unique values\n    print(f\"Number of unique values in {column} column: {non_numeric[column].nunique()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNumber of unique values in Airline column: 8\nNumber of unique values in Date_of_Journey column: 44\nNumber of unique values in Source column: 5\nNumber of unique values in Destination column: 6\nNumber of unique values in Route column: 122\nNumber of unique values in Dep_Time column: 218\nNumber of unique values in Arrival_Time column: 1220\nNumber of unique values in Duration column: 362\nNumber of unique values in Total_Stops column: 5\n```\n:::\n:::\n\n\nCuriosamente, `\"Duration\"` es actualmente una columna de tipo objeto cuando debería ser una columna numérica, ¡y tiene 362 valores únicos! Vamos a averiguar más sobre esta columna.\n\n### Categoría de duración de vuelos\n\nComo has visto, hay 362 valores únicos en la columna `\"Duration\"` de `planes`. Llamando a `planes['Duration'].head()`, vemos los siguientes valores.\n\n::: {#ad5fde9b .cell execution_count=34}\n\n::: {.cell-output .cell-output-display execution_count=13}\n```\n0        19h\n1     5h 25m\n2     4h 45m\n3     2h 25m\n4    15h 30m\nName: Duration, dtype: object\n```\n:::\n:::\n\n\nParece que no será sencillo convertirlo a números. Sin embargo, ¡podrías clasificar los vuelos por duración y examinar la frecuencia de las distintas longitudes de vuelo!\n\nCrearás una columna `\"Duration_Category\"` en el DataFrame `planes`. Antes tendrás que crear una lista de valores que deseas insertar en el DataFrame, seguida de los valores existentes a partir de los cuales deben crearse.\n\n#### Instrucciones\n\n1.  Crea una lista de categorías que contengan `\"Short-haul\"`, `\"Medium\"` y `\"Long-haul\"`.\n\n::: {#b33cf051 .cell execution_count=35}\n``` {.python .cell-code}\n# Create a list of categories\nflight_categories = ['Short-haul', 'Medium', 'Long-haul']\n```\n:::\n\n\n2.  \n\n-   Crea `short_flights`, una cadena para capturar valores de `\"0h\"`, `\"1h\"`, `\"2h\"`, `\"3h\"`, `\"4h\"` teniendo cuidado de evitar valores como `\"10h\"`.\n\n-   Crea `medium_flights` para capturar cualquier valor entre cinco y nueve horas. \\~\n\n-   Crea `long_flights` para capturar cualquier valor comprendido entre 10 y 16 horas, ambos inclusive.\n\n::: {#2a3838b3 .cell execution_count=36}\n``` {.python .cell-code}\n# Create a list of categories\nflight_categories = ['Short-haul', 'Medium', 'Long-haul']\n\n# Create short-haul values\nshort_flights = '^0h|^1h|^2h|^3h|^4h'\n\n# Create medium-haul values\nmedium_flights = '^5h|^6h|^7h|^8h|^9h'\n\n# Create long-haul values\nlong_flights = '^10h|^11h|^12h|^13h|^14h|^15h|^16h'\n```\n:::\n\n\nAhora has creado tus categorías y valores, es hora de agregar condicionalmente las categorías en el DataFrame\n\n### Añadir categorías de duración\n\nAhora que has configurado las categorías y los valores que quieres capturar, ¡es hora de construir una nueva columna para analizar la frecuencia de los vuelos según su duración!\n\nLas variables`flight_categories`, `short_flights`, `medium_flights` y `long_flights` que creaste anteriormente están a tu disposición.\n\n::: {#bd820a1d .cell execution_count=37}\n``` {.python .cell-code}\nimport numpy as np\n```\n:::\n\n\n#### Instrucciones\n\n-   Crea `conditions`, una lista que contenga subconjuntos de `planes['Duration']` basados en `short_flights`, `medium_flights` y `long_flights`.\n\n-   Crea la columna `\"Duration_Category\"` llamando a una función que acepte tu lista `conditions` y `flight_categories`, estableciendo los valores no encontrados en `\"Extreme duration\"`.\n\n-   Crea un gráfico fque muestre el recuento de cada categoría.\n\n::: {#469baf05 .cell execution_count=38}\n``` {.python .cell-code}\n# Create conditions for values in flight_categories to be created\nconditions = [\n    (planes['Duration'].str.contains(short_flights)),\n    (planes['Duration'].str.contains(medium_flights)),\n    (planes['Duration'].str.contains(long_flights))\n]\n\n# Apply the conditions list to the flight_categories\nplanes['Duration_Category'] = np.select(conditions, flight_categories,\n                                        default='Extreme duration')\n\n# Plot the counts of each categoryß\nsns.countplot(data=planes, x='Duration_Category',\n              hue='Duration_Category', legend=False)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](02_Limpieza_e_imputacion_de_datos_files/figure-html/cell-39-output-1.png){}\n:::\n:::\n\n\n¡Está claro que la mayoría de los vuelos son de corta distancia.\n\n## Trabajar con datos numéricos\n\n-   El dataset origina de los salarios\n\n::: {#4408d80a .cell execution_count=39}\n``` {.python .cell-code}\nprint(salaries.info())\n```\n:::\n\n\n![](images/paste-38.png)\n\n-   Salario en Rupias\n\n::: {#e3946de0 .cell execution_count=40}\n``` {.python .cell-code}\nprint(salaries['Salary_In_Rupees'].head())\n```\n:::\n\n\n![](images/paste-39.png)\n\n-   Convirtiendo cadena de caracteres en números\n\n    -   Remover las comas de los valores `Salary_In_Rupees`\n\n    -   Convertir la columna a tipo de dato `float`\n\n    -   Crear una nueva columna convirtiendo la moneda a dólares\n\n::: {#1186cd76 .cell execution_count=41}\n``` {.python .cell-code}\npd.Series.str.replace('Caracter a remover', 'Caracter a reemplazar')\n```\n:::\n\n\n::: {#16ac7480 .cell execution_count=42}\n``` {.python .cell-code}\nsalaries['Salary_In_Rupees'] = salaries['Salary_In_Rupees'].str.replace(',', '')\nprint(salaries['Salary_In_Rupees'].head())\n```\n:::\n\n\n![](images/paste-40.png)\n\n::: {#25ad0309 .cell execution_count=43}\n``` {.python .cell-code}\nsalaries['Salary_In_Rupees'] = salaries['Salary_In_Rupees'].astype(float) \n```\n:::\n\n\n1 Indian Rupee = 0.012 US Dollars\n\n::: {#5aff1e5b .cell execution_count=44}\n``` {.python .cell-code}\nsalaries['Salary_USD'] = salaries['Salary_In_Rupees'] * 0.012\n```\n:::\n\n\n-   Previsualizando la nueva columna\n\n::: {#f745a47f .cell execution_count=45}\n``` {.python .cell-code}\nprint(salaries[['Salary_In_Rupees', 'Salary_USD']].head())\n```\n:::\n\n\n![](images/paste-41.png)\n\n-   Añadiendo un resumen esrtadístico al DataFrame\n\n::: {#45d3d407 .cell execution_count=46}\n``` {.python .cell-code}\nsalaries.groupby('Company_Size')['Salary_USD'].mean()\n```\n:::\n\n\n![](images/paste-42.png)\n\nCalculo de la desviación estándar de los salarios por experiencia:\n\n![](images/paste-43.png)\n\n::: {#8d4d0db5 .cell execution_count=47}\n``` {.python .cell-code}\nsalaries['std_dev'] = salaries.groupby('Experience') \\ \n                      ['Salary_USD'].transform(lambda x: x.std())\n```\n:::\n\n\n::: {#e3986350 .cell execution_count=48}\n``` {.python .cell-code}\nprint(salaries[['Experience', 'std_dev']].value_counts())\n```\n:::\n\n\n![](images/paste-44.png)\n\nRepitamos el proceso para otros datos estadísticos:\n\n::: {#8845139f .cell execution_count=49}\n``` {.python .cell-code}\nsalaries['median_by_comp_size'] = salaries.groupby('Company_Size') \\\n                                  ['Salary_USD'].transform(lambda x: x.median())\n```\n:::\n\n\n::: {#c569afcd .cell execution_count=50}\n``` {.python .cell-code}\nprint(salaries[['Company_Size', 'median_by_comp_size']].head())\n```\n:::\n\n\n![](images/paste-45.png)\n\n### Duración del vuelo\n\nTe gustaría analizar la duración de los vuelos, pero por desgracia, la columna `\"Duration\"` de DataFrame `planes` contiene actualmente valores de cadena.\n\nTendrás que limpiar la columna y convertirla al tipo de datos correcto para el análisis.\n\n::: {#2a27c0be .cell execution_count=51}\n``` {.python .cell-code}\nimport re\n\ndef duration_to_decimal_str(duration_str: str) -> str:\n    '''\n    Convierte una duración de vuelo de formato '2h 30m' a una cadena en formato decimal en horas, como '2.5h'.\n    \n    Parámetros:\n    -----------\n    duration_str : str\n        Cadena de texto que representa la duración de un vuelo, como '2h 30m', '45m', '19h', etc.\n\n    Retorna:\n    --------\n    str\n        Cadena con duración expresada en horas decimales, con un solo decimal y el sufijo 'h'. Ej: '2.5h'\n    '''\n    horas = re.search(r'(\\d+)\\s*h', duration_str)\n    minutos = re.search(r'(\\d+)\\s*m', duration_str)\n\n    h = int(horas.group(1)) if horas else 0\n    m = int(minutos.group(1)) if minutos else 0\n\n    decimal_hours = round(h + m / 60, 1)\n    return f'{decimal_hours}h'\n\n\n\nplanes['Duration'] = planes['Duration'].apply(duration_to_decimal_str)\n```\n:::\n\n\n#### Instrucciones\n\n1.  Imprime los cinco primeros valores de la columna `\"Duration\"`.\n\n::: {#e71c16f3 .cell execution_count=52}\n``` {.python .cell-code}\n# Preview the column\nprint(planes['Duration'].head())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n0    19.0h\n1     5.4h\n2     4.8h\n3     2.4h\n4    15.5h\nName: Duration, dtype: object\n```\n:::\n:::\n\n\n2.  Retira `\"h\"` de la columna\n\n::: {#7671c4c9 .cell execution_count=53}\n``` {.python .cell-code}\n# Remove the string character\nplanes['Duration'] = planes['Duration'].str.replace('h', '')\nprint(planes['Duration'].head())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n0    19.0\n1     5.4\n2     4.8\n3     2.4\n4    15.5\nName: Duration, dtype: object\n```\n:::\n:::\n\n\n3.  Convierte la columna al tipo de datos `float`.\n\n::: {#8bfe3afb .cell execution_count=54}\n``` {.python .cell-code}\n# Convert to float data type\nplanes['Duration'] = planes['Duration'].astype(float)\nprint(planes['Duration'].head())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n0    19.0\n1     5.4\n2     4.8\n3     2.4\n4    15.5\nName: Duration, dtype: float64\n```\n:::\n:::\n\n\n4.  Traza un histograma de los valores de `\"Duration\"`\n\n::: {#5f7c0455 .cell execution_count=55}\n``` {.python .cell-code}\n# Plot a histogram\nsns.histplot(data=planes, x='Duration')\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](02_Limpieza_e_imputacion_de_datos_files/figure-html/cell-56-output-1.png){}\n:::\n:::\n\n\n### Añadir estadísticas descriptivas\n\nAhora `\"Duration\"` y `\"Price\"`contienen valores numéricos en el DataFrame `planes`, y te gustaría calcular para ellos estadísticas de resumen condicionadas a los valores de otras columnas.\n\n#### Instrucciones\n\n1.  Añade una columna a `planes` que contenga la desviación estándar de `\"Price\"` basada en `\"Airline\"`.\n\n::: {#67bd4d63 .cell execution_count=56}\n``` {.python .cell-code}\n# Price standard deviation by Airline\nplanes['airline_price_st_dev'] = planes.groupby('Airline')['Price'].transform(lambda x: x.std())\nprint(planes[['Airline', 'airline_price_st_dev']].value_counts())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAirline            airline_price_st_dev\nJet Airways        4159.846432             3082\nIndiGo             2245.529140             1632\nAir India          3692.609285             1399\nMultiple carriers  3558.323763              959\nSpiceJet           1798.900648              653\nVistara            2888.915498              376\nAir Asia           1979.826234              260\nGoAir              2764.926625              147\nName: count, dtype: int64\n```\n:::\n:::\n\n\n2.  Calcula la mediana de `\"Duration\"` en `\"Airline\"`, almacenándola como una columna llamada `\"airline_median_duration\"`.\n\n::: {#71cff449 .cell execution_count=57}\n``` {.python .cell-code}\n# Median Duration by Airline\nplanes['airline_median_duration'] = planes.groupby('Airline')['Duration'].transform(lambda x: x.median())\nprint(planes[['Airline', 'airline_median_duration']].value_counts())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAirline            airline_median_duration\nJet Airways        13.3                       3082\nIndiGo             2.9                        1632\nAir India          15.5                       1399\nMultiple carriers  10.2                        959\nSpiceJet           2.5                         653\nVistara            3.2                         376\nAir Asia           2.8                         260\nGoAir              2.9                         147\nName: count, dtype: int64\n```\n:::\n:::\n\n\n3.  Encuenta la media `\"Price\"` por `\"Destination\"`, guardándola como una columna llamada `\"price_destination_mean\"`.\n\n::: {#a2ab9f2e .cell execution_count=58}\n``` {.python .cell-code}\n# Mean Price by Destination\nplanes['price_destination_mean'] = planes.groupby('Destination')['Price'].transform(lambda x: x.mean())\nprint(planes[['Destination', 'price_destination_mean']].value_counts())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDestination  price_destination_mean\nCochin       10473.585927              3631\nBanglore     9093.622872               2291\nDelhi        5248.541082                998\nNew Delhi    11579.306944               720\nHyderabad    5190.274021                562\nKolkata      4907.156863                306\nName: count, dtype: int64\n```\n:::\n:::\n\n\nParece que Jet Airways tiene la mayor desviación estándar en precio, Air India tiene la mayor duración median, y Nueva Delhi, en promedio, es el destiono más caro. Ahora veamos cómo manejar los datos atípicos.\n\n## Gestión de valores atípicos\n\n-   Qué es un outlier?\n    -   Es una observación que está muy alejada de otros puntos de datos.\n-   Usando estadística descriptiva\n\n::: {#6caa285f .cell execution_count=59}\n``` {.python .cell-code}\nprint(salaries['Salary_USD'].describe())\n```\n:::\n\n\n![](images/paste-46.png)\n\n-   Usando el rango intercuartil\n\n    -   Rango intercuartil (IQR)\n\n        -   IQR = 75th - 25th percentil\n\n        -   Upper outliers \\> 75th percentile + (1.5 \\* IQR)\n\n        -   Lower Outliers \\< 25th percentile - (1.5 \\* IQR)\n\n::: {#67301411 .cell execution_count=60}\n``` {.python .cell-code}\nsns.boxplot(data=salaries, y='Salaary_USD')\nplt.show()\n```\n:::\n\n\n![](images/paste-47.png)\n\n-   Identificando Umbrales\n\n::: {#efaef0c8 .cell execution_count=61}\n``` {.python .cell-code}\n# 75th percentil\nseventy_fifth = salaries['Salary_USD'].quantile(0.75)\n\n# 25th percentil\ntwenty_fifth = salaries['Salary_USD'].quantile(0.25)\n\n# Interquartil range\nsalaries_iqr = seventy_fifth - twenty_fifth\n\nprint(salaries_iqr)\n```\n:::\n\n\n![](images/paste-48.png)\n\n::: {#5e5ddcac .cell execution_count=62}\n``` {.python .cell-code}\n# Upper threshold\nupper = seventy_fifth + (1.5 * salaries_iqr)\n\n# Lower threshold\nlower = twenty_fifth - (1.5 * salaries_iqr)\n\nprint(upper, lower)\n```\n:::\n\n\n![](images/paste-49.png)\n\n-   Subdividiendo nuestros datos\n\n::: {#87ee45b9 .cell execution_count=63}\n``` {.python .cell-code}\nsalaries[(salaries['Salary_USD'] < lower) | (salaries['Salary_USD'] > upper)] \\\n        [['Experience', 'Employee_Location', 'Salary_USD']]\n```\n:::\n\n\n![](images/paste-50.png)\n\n-   ¿ Por qué buscar los Outliers?\n\n    -   Los Outliers son valores extremos\n\n        -   Pueden no representar con precisión los datos\n\n    -   Pueden sesgar la media y la desviación estándar\n\n    -   Pruebas de estadística y modelos de machine learning requieren datos que tengan una distribución normal y no esten sesgados.\n\n-   Qué hacer con los Outliers?\n\n    -   Preguntas que nos debemos hacer:\n\n        -   Por qué existen los outliers?\n\n        -   Los valores son precisos?\n\n-   Eliminación de Outliers\n\n::: {#50207fbd .cell execution_count=64}\n``` {.python .cell-code}\nno_outliers = salaries[(salaries['Salar_USD'] > lower) & (salaries['Salary_USD'] < upper)]\n```\n:::\n\n\n::: {#5905ab16 .cell execution_count=65}\n``` {.python .cell-code}\nprint(no_outliers['Salary_USD'].describe())\n```\n:::\n\n\n![](images/paste-51.png)\n\n-   Distribución de Salarios\n\n![](images/paste-52.png)\n\n### Qué hacer con los valores atípicos?\n\nIdentificar los valores atípicos es un paso integral en la realización de análisis exploratorios de datos.\n\nEn este ejercicio, se te presentarán escenarios en los que hay valores atípicos, y tendrás que decidir qué acción debes tomar.\n\n#### Instrucciones\n\n-   Coloca cada escenario en el cubo adecuado en función del enfoque que deba adaptarse para tratar los valores atípicos.\n\n    | Elimina los valores atípicos | Dejar los valores atípicos en el conjunto de datos |\n    |----|----|\n    | Un sensor de temperatura tiene un registro de 100 grados Celsius, pero el sensor solo funciona correctamente a temperaturas de hasta 80 grados. | se registran las alturas de distintos animales y uno de ellos es más de 1.5 veces la IQR más el percentil 75. |\n    | La velocidad de un coche se registra como 5000 km/h. | Los países tienen una superficie total media de 667.143 km2, pero un país tiene 1.637.687 km2. |\n    | Un participante en un estudio tiene una edad de menos 35 años. | Un jugador de baloncesto hace una media de 35 puntos por partido cuando la media en toda la liga es de solo 10 puntos por partido. |\n\nPuede ser difícil decidir qué hacer con los valores atípicos, pero debes saber cómo gestionarlos, ¡ya que a menudo se dan en el mundo real!\n\n\n### Identificar valores atípicos\n\nHas demostrado que reconoces qué hacer cuando se te presentan valores atípicos, pero ¿Puedes identificarlos utilizando visualizaciones?\n\nIntenta averiguar si hay valores atípicos en las columnas `\"Price\"` o `\"Duration\"` del dataframe `planes`.\n\n#### Intrucciones\n\n1. Traza la distribución de la columna `\"Price\"` de `planes`.\n\n::: {#88b68873 .cell execution_count=66}\n``` {.python .cell-code}\n# Plot a histogram of flight prices\nsns.histplot(data=planes, x='Price')\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](02_Limpieza_e_imputacion_de_datos_files/figure-html/cell-67-output-1.png){}\n:::\n:::\n\n\n2. Muestra las estadísticas descriptivas de la duración del vuelo.\n\n::: {#48b6b7c0 .cell execution_count=67}\n``` {.python .cell-code}\n# Display descriptive statistics for flight duration\nprint(planes['Duration'].describe())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncount    8508.000000\nmean       10.726704\nstd         8.472415\nmin         0.100000\n25%         2.800000\n50%         8.700000\n75%        15.500000\nmax        47.700000\nName: Duration, dtype: float64\n```\n:::\n:::\n\n\n3. **Pregunta**\n\n¿Qué columna contiene potencialmente valores atípicos?\n\n**Respuestas Posibles**\n\n- [ ] `\"Price\"`\n- [ ] `\"Duration\"`\n- [x] `\"Price\"` y `\"Duration\"`\n- [ ] Ninguna\n\nLos histogramas, diagramas de caja y estadísticas descriptivas también son métodos útiles para identificar valores extremos. ¡Ahora vamos a tratarlos!\n\n\n### Eliminar valores atípicos\n\nAunque eliminar los valores atípicos no siempre es el camino a seguir, para tu análisis has decidido que solo incluirás los vuelos en los que el `\"Price\"` no sea un valor atípico.\n\nPor lo tanto tienes que encontrar el umbral superior y utilizarlo para eliminar los valores que lo superen del Dataframe `planes`.\n\n#### Instrucciones\n\n1. Halla los percentiles 75 y 25, guardando como `price_seventy_fifth` y `price_twenty_fifth` respectivamente.\n\n::: {#ffdb0b88 .cell execution_count=68}\n``` {.python .cell-code}\n# Find the 75th and 25th percentiles\nprice_seventy_fifth = planes['Price'].quantile(0.75)\nprice_twenty_fifth = planes['Price'].quantile(0.25)\n```\n:::\n\n\n2. Calcula el IQR, almacenándolo como `prices_iqr`.\n\n::: {#cb379404 .cell execution_count=69}\n``` {.python .cell-code}\n# Calculate iqr\nprices_iqr = price_seventy_fifth - price_twenty_fifth\nprint(prices_iqr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n7014.0\n```\n:::\n:::\n\n\n3. Calcula los umbrales superior e inferior de los valores atípicos.\n\n::: {#abc22625 .cell execution_count=70}\n``` {.python .cell-code}\n# Calculate the thresholds\nupper = price_seventy_fifth + (1.5 * prices_iqr)\nlower = price_twenty_fifth - (1.5 * prices_iqr)\n```\n:::\n\n\n4. Elimina los valores atípicos de `planes`.\n\n::: {#0104a505 .cell execution_count=71}\n``` {.python .cell-code}\n# Subset the data\nplanes = planes[(planes['Price'] > lower) & (planes['Price'] < upper)]\n\nprint(planes['Price'].describe())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncount     8438.000000\nmean      8877.466046\nstd       4001.838236\nmin       1759.000000\n25%       5224.000000\n50%       8372.000000\n75%      12121.000000\nmax      22270.000000\nName: Price, dtype: float64\n```\n:::\n:::\n\n\n¡Habilidades ridículas para eliminar valores atípicos! Lograste crear umbrales basados en el IQR y los usaste para filtrar el conjunto de datos `planes` para eliminar precios extremos. Originalmente, el conjunto de datos tenía un precio máximo de casi 55000, pero la salida de `planes['Price'].describe()` muestra que el máximo se ha reducido a alrededor de 23000, ¡reflejando una distribución menos sesgada para el análisis!\n\n",
    "supporting": [
      "02_Limpieza_e_imputacion_de_datos_files"
    ],
    "filters": [],
    "includes": {}
  }
}