# Bienvenida {.unnumbered}

游늵 Nivel: Principiante  
游 Duraci칩n estimada: 4 horas  
游꿘 Incluye c칩digo, visualizaciones y ejercicios

---

## Descripcion
Aprender Python es crucial para cualquier aspirante a profesional de ciencia de datos. Aprende a visualizar datos reales con las funciones de Matplotlib y familizarizarte con estructuras de datos como el diccionario y el DataFrame de pandas. Este curso intermedio de 4 horas te ayudar치 a mejorar tus conocimientos de Python y a explorar nuevas aplicaciones y funciones de Python que amplien tu repertorio y te ayuden a trabajar con m치s eficacia.

Descubrir치s c칩mo los diccionarios ofrecen una alternativa a las listas de Python, y por qu칠 el marco de datos de pandas es la forma m치s popular de trabajar con datos tabulares. En el segundo cap칤tulo de este curso, descubrir치s c칩mo puedes crear y manipular conjuntos de datos, y c칩mo acceder a ellos utilizando estas estructuras. La pr치ctica a lo largo del curso aumentar치 tu confianza en cada 치rea.

A medida que avances, estudiar치s la l칩gica, el flujo de control, el filtrado y los bucles. Estas funciones sirven para controlar la toma de decisiones en los programas Python y te ayudan a realizar m치s operaciones con tus datos, incluidas las declaraciones repetidas. Terminar치s el curso aplicando todas tus nuevas habilidades con estad칤sticas de hacker para calcular tus posibilidades de ganar una apuesta.

Una vez que hayas completado todos los cap칤tulos, estar치s listo para aplicar tus nuevas habilidades en tu trabajo, nueva carrera o proyecto personal, y estar치s preparado para pasar a un aprendizaje m치s avanzado de Python.

## Lo que aprender치s
- Identificar y aplicar funciones de Matplotlib para crear gr치ficos de l칤neas, dispersi칩n e histogramas.
- Aprende a crear, actualizar y manipular diccionarios y DataFrames de pandas.
- Distinguir entre operadores de comparaci칩n, booleanos y l칩gicos, y evaluar su uso en el filtrado de datos.
- Identifica el uso de blucles (for, while) y apl칤calos para iterar sobre listas, diccionarios, arreglos Numpy y DataFrame de pandas.
- Eval칰a la generaci칩n de n칰meros aleatorios y las simulaciones (paseos aleatorios, distribuciones) para analizar probabilidades y resultados.


## M칩dulos del curso

1. [Matplotlib](01_Matplotlib.qmd)
2. [Diccionarios y Pandas](02_Diccionarios_y_pandas.qmd)
3. [L칩gica, Flujo de Control y Filtrado](03_Logica_flujo_de_control_y_filtrado.qmd)
4. [Bucles](04_Bucles.qmd)
5. [Caso Pr치ctico: Estad칤stica de hacker](05_Caso_practico.qmd)