# Bienvenida {.unnumbered}

游늵 Nivel: Intermedio  
游 Duraci칩n estimada: 4 horas  
游꿘 Incluye c칩digo, visualizaciones y ejercicios

---

## Descripci칩n

El muestreo en Python es la piedra angular de la estad칤stica de inferencia y las pruebas de hip칩tesis. Es una poderosa habilidad utilizada en el an치lisis de encuestas y el dise침o experimental para sacar conclusiones sin encuestar a toda una poblaci칩n. En este curso de Muestreo en Python, descubrir치s cu치ndo utilizar el muestreo y c칩mo realizar tipos comunes de muestreo, desde el muestreo aleatorio simple hasta m칠todos m치s complejos como el muestreo estratificado y por cl칰steres. Utilizando conjuntos de datos del mundo real, como valoraciones de caf칠, canciones de Spotify y bajas de empleados, aprender치s a estimar estad칤sticas de poblaci칩n y a cuantificar la incertidumbre en tus estimaciones generando distribuciones de muestreo y distribuciones bootstrap.

## M칩dulos del curso

1. [Introducci칩n al muestreo](01_Introduccion_al_muestreo.qmd)
2. [M칠todos de muestreo](02_Metodos_de_muestreo.qmd)
3. [Distribuciones muestrales](03_Distribuciones_muestrales.qmd)
4. [Distribuciones Bootstrap](04_Distribuciones_bootstrap.qmd)
