# Bienvenida {.unnumbered}

 Nivel: Intermedio  
 Duración estimada: 4 horas  
 Incluye código, visualizaciones y ejercicios

---

# Descripción

Ser capaz de combinar y trabajar con múltiples conjuntos de datos es una habilidad esencial para cualquier aspirante a científico de datos. pandas es una piedra angular crucial del ecosistema de ciencia de datos de Python, y Stack Overflow registra 5 millones de visitas a preguntas sobre pandas. Aprende a manejar múltiples DataFrames combinándolos, organizándolos, uniéndolos y remodelándolos mediante pandas. Trabajarás con conjuntos de datos del Banco Mundial y de la ciudad de Chicago. Terminarás el curso con un sólido conjunto de habilidades para unir datos en pandas.

## Módulos del curso

1. [Conceptos básicos de la fusión de datos](01_Conceptos_basicos_de_la_fusion_de_datos.qmd)
2. [Fusionar tablas con distintos tipos de unión](02_Fusionar_tablas_distintos_tipos.qmd)
3. [Fusión y concatenación avanzadas](03_Fusion_y_concatenacion_avanzadas.qmd)
4. [Fusionar datos ordenados y series temporales](04_Fusionar_datos_ordenados_y_series_temporales.qmd)

## Datasets

Este curso utiliza los siguientes archivos:

- 