# Bienvenida {.unnumbered}

游늵 Nivel: Principiante  
游 Duraci칩n estimada: 4 horas  
游꿘 Incluye c칩digo, visualizaciones y ejercicios

---

## Descripcion
Python es un lenguaje de programaci칩n de uso general cada vez m치s popular para la ciencia de datos. Empresas de todo el mundo utilizan Python para extraer informaci칩n de sus datos y obtener una ventaja competitiva. A diferencia de otros tutoriales de Python, este curso se centra en Python espec칤ficamente para la ciencia de datos. En nuestro curso de Introducci칩n a Python aprender치s potentes formas de almacenar y manipular datos y conocer치s 칰tiles herramientas de ciencias de datos para empezar a realizar tus propios an치lisis. 

## Lo que aprender치s
- Identificar los tipos de datos de Python (int, float, str, bool) y utilizarlos en c치lculos y variables.
- Reconocer c칩mo crear, subconjuntar y modificar listas, inclu칤das las listas anidadas.
- Diferenciar entre funciones , m칠todos y paquetes, y aplicarlos para resolver tareas.
- Identificar los arreglos Numpy, distinguirlas de las listas y evaluar su funci칩n en el an치lisis de datos.
- Eval칰a las herramientas estad칤sticas de Numpy (media, mediana, desviaci칩n est치ndar, correlaci칩n) para obtener informaci칩n sobre los datos.


## M칩dulos del curso

1. [Conceptos B치sicos de Python](01_Conceptos_basicos_de_python.qmd)
2. [Listas Python](02_Listas_python.qmd)
3. [Funciones y Paquetes](03_Funciones_y_paquetes.qmd)
4. [Numpy](04_Numpy.qmd)