# Bienvenida {.unnumbered}

游늵 Nivel: Principiante  
游 Duraci칩n estimada: 4 horas  
游꿘 Incluye c칩digo, visualizaciones y ejercicios

---

## Descripcion

Pandas es la biblioteca de Python m치s popular del mundo, utilizada para todo, desde la manipulaci칩n de datos hasta el an치lisis de datos. En este curso, aprender치s a manipular los DataFrames, mientras extraes, filtras y transformas conjuntos de datos del mundo real para su an치lisis. Utilizando pandas explorar치s todos los conceptos b치sicos de la ciencia de datos. Utilizando datos del mundo real, como cifras de ventas de Walmart y series temporales de temperatura global, aprender치s a importar, limpiar, calcular estad칤sticas y crear visualizaciones, 춰utilizando pandas para aumentar la potencia de Python!

## M칩dulos del curso

1. [Transformaci칩n de DataFrames](01_Transformacion_de_dataframes.qmd)
2. [Agregar DataFrames](02_Agregar_dataframes.qmd)
3. [Segmentar e indexar DataFrames](03_Segmentar_e_indexar_dataframes.qmd)
4. [Crear y visualizar DataFrames](04_Crear_y_visualizar_dataframes.qmd)
