# Bienvenida {.unnumbered}

游늵 Nivel: Intermedio  
游 Duraci칩n estimada: 4 horas  
游꿘 Incluye c칩digo, visualizaciones y ejercicios

---

## Descripci칩n

La estad칤stica es el estudio de c칩mo recopilar, analizar y extraer conclusiones a partir de los datos. Es una herramienta enormemente valiosa que puedes utilizar para enfocar el futuro e inferir la respuesta a montones de preguntas. Por ejemplo, 쯖u치l es la probabilidad de que alguien compre tu producto, cu치ntas llamadas recibir치 tu equipo de asistencia y cu치ntas tallas de vaqueros deber칤as fabricar para que le queden bien al 95 % de la poblaci칩n? En este curso, descubrir치s c칩mo responder a preguntas como estas a medida que aumentas tus competencias estad칤sticas y aprendes a calcular medias, utilizar diagramas de dispersi칩n para mostrar la relaci칩n entre valores num칠ricos y calcular la correlaci칩n. Tambi칠n abordar치s la probabilidad, columna vertebral del razonamiento estad칤stico, y aprender치s a utilizar Python para realizar un estudio bien dise침ado que te permita extraer tus propias conclusiones a partir de los datos.

## M칩dulos del curso

1. [S칤ntesis estad칤stica](01_Sintesis_estadistica.qmd) 
2. [N칰meros aleatorios y probabilidad](02_Numeros_aleatorios_y_probabilidad.qmd)
3. [M치s distribuciones y el teorema del l칤mite central](03_Mas_distribuciones_y_teorema_limite_central.qmd)
4. [Correlaci칩n y dise침o de experimentos](04_Correlacion_y_diseno_de_experimentos.qmd)

## Datasets

Este curso utiliza los siguientes archivos:

- `amir_deals.csv`
- `food_consumption.csv`
- `world_happiness_add_sugar.csv`
- `world_happiness.csv`